### ISSUE TITLE
Add contact email to code of conduct

### ISSUE THREAD

**Issue by vsoch** [good-labs/.github#1]
@pdurbin let's chat about the best contact means for the code of conduct - there should probably be a private and community channel to ask questions, etc.

**Comment by pdurbin** [comment]
@publiclab has a very well thought out code of conduct including means of contact: https://publiclab.org/conduct

**Comment by vsoch** [comment]
@pdurbin do you want to spin up a modified version and PR here? I was using the contributor's covenant because it's popular, but I agree that a custom written one would be absolutely better.

**Comment by pdurbin** [comment]
Well, I like working in small chunks so I think closing out this issue by adding an email address or two will suffice. Perhaps some day we can create a new issue rethinking the whole thing.

**Comment by vsoch** [comment]
@pdurbin do you want to create a different code of conduct or not? If you don't want to do the work just tell me and I'll do it. If you think this is important, we don't close the issue - we make the change. if you have changed your mind and it's not important, then we close the issue. Let me know.

**Comment by pdurbin** [comment]
I agree with the original issue. An email should be added. I fear scope creep. No, I don't want to create a different code of conduct. Perhaps I shouldn't have linked to Public Lab's. I didn't mean to imply that there's anything wrong with the one you've chosen.

**Comment by vsoch** [comment]
ah okay! So I'll look into murmur and see if it supports adding an org email. If not, I'll add mine. Good plan :)

**Comment by vsoch** [comment]
Added, the admin contact is good-labs+admins@murmur.csail.mit.edu and the primary contact is that (minus the admin). I'm going to try and figure out how a (non member / interested person) is able to join (and I sent you an invite).
